#!/usr/bin/env python3
"""
CockpitOS Display Generator Wrapper
====================================
Thin wrapper - all logic lives in ../_core/display_gen_core.py
DO NOT EDIT THIS FILE - edit the core module instead.
"""
import os, sys
os.chdir(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..', '_core'))
from display_gen_core import run
run()
