// THIS FILE IS AUTO-GENERATED; ONLY EDIT INDIVIDUAL LED/GAUGE RECORDS, DO NOT ADD OR DELETE THEM HERE
#pragma once

// Embedded LEDMapping structure and enums
enum LEDDeviceType {
  DEVICE_GPIO,
  DEVICE_NONE,
  DEVICE_GAUGE,
  DEVICE_GN1640T,
  DEVICE_TM1637,
  DEVICE_PCA9555,
  DEVICE_WS2812,
};

struct LEDMapping {
  const char* label;
  LEDDeviceType deviceType;
  union {
    struct { uint8_t gpio; } gpioInfo;
    struct { uint8_t gpio; uint16_t minPulse; uint16_t maxPulse; uint16_t period; } gaugeInfo;
    struct { uint8_t address; uint8_t port; uint8_t bit; } pcaInfo;
    struct { uint8_t clkPin; uint8_t dioPin; uint8_t segment; uint8_t bit; } tm1637Info;
    struct { uint8_t address; uint8_t column; uint8_t row; } gn1640Info;
    struct { uint8_t index; } ws2812Info;
  } info;
  bool dimmable;
  bool activeLow;
};

// Auto-generated panelLEDs array
static const LEDMapping panelLEDs[] = {
  { "ADI_AUX_FLAG"               , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "ADI_BANK"                   , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "ADI_BUBBLE"                 , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "ADI_GS_BAR"                 , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "ADI_GS_FLAG"                , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "ADI_GS_POINTER"             , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "ADI_LOC_BAR"                , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "ADI_LOC_FLAG"               , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "ADI_OFF_FLAG"               , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "ADI_PITCH"                  , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "ADI_PITCH_TRIM"             , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "ADI_TURNRATE"               , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "AIRSPEED"                   , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "MACH_INDICATOR"             , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "MAX_AIRSPEED"               , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "SET_AIRSPEED"               , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "ALT_10000_FT_CNT"           , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "ALT_1000_FT_CNT"            , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "ALT_100_FT_CNT"             , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "ALT_100_FT_PTR"             , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "ALT_PNEU_FLAG"              , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "ALT_PRESSURE_DRUM_0_CNT"    , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "ALT_PRESSURE_DRUM_1_CNT"    , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "ALT_PRESSURE_DRUM_2_CNT"    , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "ALT_PRESSURE_DRUM_3_CNT"    , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "AOA_VALUE"                  , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "COMM1_PWR_KNB"              , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "COMM2_PWR_KNB"              , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "ILS_PWR_KNB"                , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "INTERCOM_KNB"               , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "MSL_KNB"                    , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "SEC_VOICE_KNB"              , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "TACAN_KNB"                  , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "TF_KNB"                     , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "THREAT_KNB"                 , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "CLOCK_CURRTIME_H"           , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "CLOCK_CURRTIME_MS"          , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "CLOCK_ELAPSED_TIME_M"       , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "CLOCK_ELAPSED_TIME_SEC"     , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "CANOPY_LOCK"                , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "CANOPY_POS"                 , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "SEAT_HEIGHT"                , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "PITCH_TRIM"                 , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "ROLL_TRIM"                  , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "YAW_TRIM"                   , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "ECM_DIM_KNB"                , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "TEMP_KNB"                   , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "HYDRAZIN_VOLUME"            , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "ENGINE_FTIT"                , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "ENGINE_NOZZLE_POSITION"     , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "ENGINE_OIL_PRESSURE"        , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "ENGINE_TACHOMETER"          , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "AIR_REFUEL_LIGHT_KNB"       , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "FORM_LIGHT_KNB"             , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "FUELFLOWCOUNTER_100"        , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "FUELFLOWCOUNTER_10K"        , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "FUELFLOWCOUNTER_1K"         , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "FUELTOTALIZER_100"          , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "FUELTOTALIZER_10K"          , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "FUELTOTALIZER_1K"           , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "FUEL_AL"                    , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "FUEL_FR"                    , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "HMCS_INT_KNB"               , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "SYSA_PRESSURE"              , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "SYSB_PRESSURE"              , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "IFF_CODE_DRUM_DIGIT_1"      , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "IFF_CODE_DRUM_DIGIT_2"      , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "IFF_CODE_DRUM_DIGIT_3"      , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "IFF_CODE_DRUM_DIGIT_4"      , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "AOA_INDEX_BRT_KNB"          , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "AR_STATUS_BRT_KNB"          , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "FLOOD_CONSOLES_BRT_KNB"     , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "FLOOD_INST_PNL_BRT_KNB"     , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "PRI_CONSOLES_BRT_KNB"       , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "PRI_DATA_DISPLAY_BRT_KNB"   , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "PRI_INST_PNL_BRT_KNB"       , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "LIGHT_CONSLES"              , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "LIGHT_CONSLES_FLOOD"        , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "LIGHT_INST_PNL"             , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "LIGHT_INST_PNL_FLOOD"       , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "KY58_VOL_KNB"               , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "COCKPIT_ALITITUDE"          , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "FLOW_INDICATOR"             , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "FLOW_INDICATOR_LIGHT"       , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "OXYGEN_PRESSURE"            , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "RWR_IND_DIM_KNB"            , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "RWR_INTENS_KNB"             , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "SAI_AIRCRAFTREFERENCESYMBOL", DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "SAI_BANK"                   , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "SAI_BANK_ARROW"             , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "SAI_KNB_ARROW"              , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "SAI_OFF_FLAG"               , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "SAI_PITCH"                  , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "SAI_PITCH_TRIM"             , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "SPEEDBRAKE_INDICATOR"       , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "STANDBY_COMPASS_HEADING"    , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "STANDBY_COMPASS_PITCH"      , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "STANDBY_COMPASS_ROLL"       , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "PITCHTRIMIND"               , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "ROLLTRIMIND"                , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "ICP_HUD_BRT_KNB"            , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "ICP_RASTER_BRT_KNB"         , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "ICP_RASTER_CONTR_KNB"       , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "ICP_RETICLE_DEPRESS_KNB"    , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "UHF_VOL_KNB"                , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "VVI"                        , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "LIGHT_ACFT_BATT_FAIL"       , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "LIGHT_ACTIVE"               , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "LIGHT_AFT_FUEL_LOW"         , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "LIGHT_AIR"                  , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "LIGHT_ANTI_SKID"            , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "LIGHT_AOA_DN"               , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "LIGHT_AOA_MID"              , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "LIGHT_AOA_UP"               , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "LIGHT_AR_NWS"               , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "LIGHT_ATF_NOT"              , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "LIGHT_AVIONICS_FAULT"       , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "LIGHT_BUC"                  , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "LIGHT_CABIN_PRESS"          , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "LIGHT_CADC"                 , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "LIGHT_CANOPY"               , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "LIGHT_CAUTION_1"            , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "LIGHT_CAUTION_2"            , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "LIGHT_CAUTION_3"            , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "LIGHT_CAUTION_4"            , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "LIGHT_CAUTION_5"            , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "LIGHT_CAUTION_6"            , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "LIGHT_CMDS_DISP"            , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "LIGHT_CMDS_GO"              , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "LIGHT_CMDS_NO_GO"           , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "LIGHT_CMDS_RDY"             , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "LIGHT_DBU_ON"               , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "LIGHT_DISC"                 , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "LIGHT_ECM"                  , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "LIGHT_ECM_1_A"              , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "LIGHT_ECM_1_F"              , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "LIGHT_ECM_1_S"              , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "LIGHT_ECM_1_T"              , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "LIGHT_ECM_2_A"              , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "LIGHT_ECM_2_F"              , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "LIGHT_ECM_2_S"              , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "LIGHT_ECM_2_T"              , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "LIGHT_ECM_3_A"              , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "LIGHT_ECM_3_F"              , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "LIGHT_ECM_3_S"              , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "LIGHT_ECM_3_T"              , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "LIGHT_ECM_4_A"              , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "LIGHT_ECM_4_F"              , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "LIGHT_ECM_4_S"              , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "LIGHT_ECM_4_T"              , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "LIGHT_ECM_5_A"              , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "LIGHT_ECM_5_F"              , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "LIGHT_ECM_5_S"              , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "LIGHT_ECM_5_T"              , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "LIGHT_ECM_A"                , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "LIGHT_ECM_F"                , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "LIGHT_ECM_FRM_A"            , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "LIGHT_ECM_FRM_F"            , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "LIGHT_ECM_FRM_S"            , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "LIGHT_ECM_FRM_T"            , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "LIGHT_ECM_S"                , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "LIGHT_ECM_SPL_A"            , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "LIGHT_ECM_SPL_F"            , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "LIGHT_ECM_SPL_S"            , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "LIGHT_ECM_SPL_T"            , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "LIGHT_ECM_T"                , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "LIGHT_EDGE"                 , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "LIGHT_EEC"                  , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "LIGHT_ELEC"                 , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "LIGHT_ELEC_SYS"             , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "LIGHT_ENGINE"               , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "LIGHT_ENGINE_FAULT"         , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "LIGHT_ENG_FIRE"             , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "LIGHT_EPU"                  , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "LIGHT_EPU_GEN"              , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "LIGHT_EPU_PMG"              , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "LIGHT_EQUIP_HOT"            , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "LIGHT_FLCS"                 , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "LIGHT_FLCS_FAULT"           , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "LIGHT_FLCS_PMG"             , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "LIGHT_FLCS_PWR_A"           , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "LIGHT_FLCS_PWR_B"           , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "LIGHT_FLCS_PWR_C"           , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "LIGHT_FLCS_PWR_D"           , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "LIGHT_FLCS_RLY"             , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "LIGHT_FL_FAIL"              , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "LIGHT_FL_RUN"               , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "LIGHT_FUEL_OIL_HOT"         , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "LIGHT_FWD_FUEL_LOW"         , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "LIGHT_GEAR_L"               , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "LIGHT_GEAR_N"               , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "LIGHT_GEAR_R"               , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "LIGHT_GEAR_WARN"            , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "LIGHT_HOOK"                 , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "LIGHT_HYDRAZN"              , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "LIGHT_HYD_OIL_PRESS"        , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "LIGHT_IFF"                  , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "LIGHT_INLET_ICING"          , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "LIGHT_JFS_RUN"              , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "LIGHT_MAIN_GEN"             , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "LIGHT_MARKER_BEACON"        , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "LIGHT_MASTER_CAUTION"       , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "LIGHT_NUCLEAR"              , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "LIGHT_NWS_FAIL"             , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "LIGHT_OBOGS"                , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "LIGHT_OVERHEAT"             , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "LIGHT_OXY_LOW"              , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "LIGHT_PROBE_HEAT"           , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "LIGHT_RADAR_ALT"            , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "LIGHT_RDY"                  , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "LIGHT_RWR_ACTIVITY"         , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "LIGHT_RWR_ACT_POWER"        , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "LIGHT_RWR_ALT"              , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "LIGHT_RWR_ALT_LOW"          , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "LIGHT_RWR_HANDOFF_H"        , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "LIGHT_RWR_HANDOFF_UP"       , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "LIGHT_RWR_MODE_OPEN"        , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "LIGHT_RWR_MODE_PRI"         , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "LIGHT_RWR_MSL_LAUNCH"       , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "LIGHT_RWR_POWER"            , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "LIGHT_RWR_SEARCH"           , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "LIGHT_RWR_SHIP_U"           , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "LIGHT_RWR_SHIP_UNK"         , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "LIGHT_RWR_SYSTEST"          , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "LIGHT_RWR_SYSTEST_ON"       , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "LIGHT_RWR_TGTSEP_DN"        , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "LIGHT_RWR_TGTSEP_UP"        , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "LIGHT_SEAT_NOT"             , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "LIGHT_SEC"                  , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "LIGHT_STBY"                 , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "LIGHT_STBY_GEN"             , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "LIGHT_STORES_CONFIG"        , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "LIGHT_TF_FAIL"              , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "LIGHT_TO_FLCS"              , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "LIGHT_TO_LDG_CONFIG"        , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info
};

static constexpr uint16_t panelLEDsCount = sizeof(panelLEDs)/sizeof(panelLEDs[0]);

// Auto-generated hash table
struct LEDHashEntry { const char* label; const LEDMapping* led; };
static const LEDHashEntry ledHashTable[479] = {
  {"LIGHT_FLCS_PWR_B", &panelLEDs[181]},
  {"LIGHT_FLCS_PWR_C", &panelLEDs[182]},
  {"LIGHT_FLCS_PWR_D", &panelLEDs[183]},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {"FLOOD_INST_PNL_BRT_KNB", &panelLEDs[72]},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {"SAI_PITCH", &panelLEDs[92]},
  {"LIGHT_ECM_2_S", &panelLEDs[140]},
  {"KY58_VOL_KNB", &panelLEDs[80]},
  {"LIGHT_ECM_2_T", &panelLEDs[141]},
  {"LIGHT_EDGE", &panelLEDs[166]},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {"ALT_PRESSURE_DRUM_1_CNT", &panelLEDs[22]},
  {"FUEL_FR", &panelLEDs[61]},
  {"LIGHT_CMDS_DISP", &panelLEDs[127]},
  {nullptr, nullptr},
  {"CLOCK_CURRTIME_H", &panelLEDs[35]},
  {"LIGHT_RDY", &panelLEDs[209]},
  {"YAW_TRIM", &panelLEDs[44]},
  {"LIGHT_OVERHEAT", &panelLEDs[205]},
  {nullptr, nullptr},
  {"LIGHT_HYD_OIL_PRESS", &panelLEDs[195]},
  {"ALT_100_FT_PTR", &panelLEDs[19]},
  {"LIGHT_AOA_DN", &panelLEDs[111]},
  {"LIGHT_RWR_SHIP_U", &panelLEDs[221]},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {"LIGHT_ELEC", &panelLEDs[168]},
  {"LIGHT_ACFT_BATT_FAIL", &panelLEDs[106]},
  {nullptr, nullptr},
  {"AIRSPEED", &panelLEDs[12]},
  {"RWR_IND_DIM_KNB", &panelLEDs[85]},
  {"SAI_PITCH_TRIM", &panelLEDs[93]},
  {"ILS_PWR_KNB", &panelLEDs[28]},
  {"LIGHT_CABIN_PRESS", &panelLEDs[118]},
  {"LIGHT_ENGINE_FAULT", &panelLEDs[171]},
  {nullptr, nullptr},
  {"ALT_100_FT_CNT", &panelLEDs[18]},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {"LIGHT_MAIN_GEN", &panelLEDs[199]},
  {nullptr, nullptr},
  {"LIGHT_HYDRAZN", &panelLEDs[194]},
  {"LIGHT_RWR_SYSTEST_ON", &panelLEDs[224]},
  {"TEMP_KNB", &panelLEDs[46]},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {"LIGHT_AOA_MID", &panelLEDs[112]},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {"PRI_DATA_DISPLAY_BRT_KNB", &panelLEDs[74]},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {"LIGHT_CMDS_GO", &panelLEDs[128]},
  {nullptr, nullptr},
  {"ADI_BANK", &panelLEDs[1]},
  {"LIGHT_SEAT_NOT", &panelLEDs[227]},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {"FUELFLOWCOUNTER_1K", &panelLEDs[56]},
  {"LIGHT_ENGINE", &panelLEDs[170]},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {"LIGHT_MASTER_CAUTION", &panelLEDs[201]},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {"ENGINE_OIL_PRESSURE", &panelLEDs[50]},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {"LIGHT_INST_PNL", &panelLEDs[78]},
  {"LIGHT_NUCLEAR", &panelLEDs[202]},
  {nullptr, nullptr},
  {"LIGHT_CMDS_RDY", &panelLEDs[130]},
  {"LIGHT_DISC", &panelLEDs[132]},
  {"LIGHT_INST_PNL_FLOOD", &panelLEDs[79]},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {"LIGHT_TF_FAIL", &panelLEDs[232]},
  {nullptr, nullptr},
  {"ALT_PRESSURE_DRUM_0_CNT", &panelLEDs[21]},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {"HYDRAZIN_VOLUME", &panelLEDs[47]},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {"LIGHT_AOA_UP", &panelLEDs[113]},
  {"LIGHT_CONSLES_FLOOD", &panelLEDs[77]},
  {"LIGHT_GEAR_WARN", &panelLEDs[192]},
  {nullptr, nullptr},
  {"LIGHT_AFT_FUEL_LOW", &panelLEDs[108]},
  {"LIGHT_EPU_GEN", &panelLEDs[174]},
  {"FUELTOTALIZER_100", &panelLEDs[57]},
  {"LIGHT_EPU_PMG", &panelLEDs[175]},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {"LIGHT_ECM_FRM_A", &panelLEDs[156]},
  {"LIGHT_ECM_3_A", &panelLEDs[142]},
  {"LIGHT_FWD_FUEL_LOW", &panelLEDs[188]},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {"LIGHT_ECM_FRM_F", &panelLEDs[157]},
  {"LIGHT_ECM_3_F", &panelLEDs[143]},
  {nullptr, nullptr},
  {"INTERCOM_KNB", &panelLEDs[29]},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {"LIGHT_ECM_FRM_S", &panelLEDs[158]},
  {"LIGHT_ECM_3_S", &panelLEDs[144]},
  {"LIGHT_ECM_3_T", &panelLEDs[145]},
  {"FUELTOTALIZER_10K", &panelLEDs[58]},
  {"LIGHT_ECM_FRM_T", &panelLEDs[159]},
  {nullptr, nullptr},
  {"ADI_AUX_FLAG", &panelLEDs[0]},
  {"LIGHT_EPU", &panelLEDs[173]},
  {"LIGHT_RWR_POWER", &panelLEDs[219]},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {"ADI_GS_BAR", &panelLEDs[3]},
  {"THREAT_KNB", &panelLEDs[34]},
  {"TACAN_KNB", &panelLEDs[32]},
  {nullptr, nullptr},
  {"IFF_CODE_DRUM_DIGIT_1", &panelLEDs[65]},
  {"IFF_CODE_DRUM_DIGIT_2", &panelLEDs[66]},
  {"IFF_CODE_DRUM_DIGIT_3", &panelLEDs[67]},
  {"IFF_CODE_DRUM_DIGIT_4", &panelLEDs[68]},
  {"PRI_INST_PNL_BRT_KNB", &panelLEDs[75]},
  {"LIGHT_SEC", &panelLEDs[228]},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {"ALT_PNEU_FLAG", &panelLEDs[20]},
  {"CLOCK_ELAPSED_TIME_SEC", &panelLEDs[38]},
  {"LIGHT_FL_RUN", &panelLEDs[186]},
  {"LIGHT_TO_FLCS", &panelLEDs[233]},
  {"ICP_RASTER_BRT_KNB", &panelLEDs[101]},
  {nullptr, nullptr},
  {"LIGHT_RWR_HANDOFF_H", &panelLEDs[214]},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {"LIGHT_ECM_A", &panelLEDs[154]},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {"LIGHT_ECM_F", &panelLEDs[155]},
  {"LIGHT_ATF_NOT", &panelLEDs[115]},
  {"LIGHT_JFS_RUN", &panelLEDs[198]},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {"LIGHT_ECM", &panelLEDs[133]},
  {"LIGHT_ANTI_SKID", &panelLEDs[110]},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {"VVI", &panelLEDs[105]},
  {"LIGHT_FLCS_PMG", &panelLEDs[179]},
  {"LIGHT_ECM_S", &panelLEDs[160]},
  {"LIGHT_ECM_T", &panelLEDs[165]},
  {nullptr, nullptr},
  {"FLOW_INDICATOR_LIGHT", &panelLEDs[83]},
  {"LIGHT_DBU_ON", &panelLEDs[131]},
  {"LIGHT_PROBE_HEAT", &panelLEDs[207]},
  {"FLOW_INDICATOR", &panelLEDs[82]},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {"AOA_VALUE", &panelLEDs[25]},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {"ECM_DIM_KNB", &panelLEDs[45]},
  {nullptr, nullptr},
  {"LIGHT_STBY", &panelLEDs[229]},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {"LIGHT_STBY_GEN", &panelLEDs[230]},
  {"SAI_BANK_ARROW", &panelLEDs[89]},
  {"ALT_10000_FT_CNT", &panelLEDs[16]},
  {"ICP_RETICLE_DEPRESS_KNB", &panelLEDs[103]},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {"LIGHT_RWR_TGTSEP_DN", &panelLEDs[225]},
  {"CANOPY_POS", &panelLEDs[40]},
  {"FUELFLOWCOUNTER_100", &panelLEDs[54]},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {"LIGHT_ELEC_SYS", &panelLEDs[169]},
  {"CLOCK_ELAPSED_TIME_M", &panelLEDs[37]},
  {"LIGHT_RWR_ALT", &panelLEDs[212]},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {"SYSB_PRESSURE", &panelLEDs[64]},
  {"LIGHT_EEC", &panelLEDs[167]},
  {"LIGHT_EQUIP_HOT", &panelLEDs[176]},
  {"LIGHT_NWS_FAIL", &panelLEDs[203]},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {"MACH_INDICATOR", &panelLEDs[13]},
  {nullptr, nullptr},
  {"ROLLTRIMIND", &panelLEDs[99]},
  {"ENGINE_NOZZLE_POSITION", &panelLEDs[49]},
  {"FUELFLOWCOUNTER_10K", &panelLEDs[55]},
  {"LIGHT_ECM_4_A", &panelLEDs[146]},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {"LIGHT_ECM_4_F", &panelLEDs[147]},
  {"LIGHT_OBOGS", &panelLEDs[204]},
  {nullptr, nullptr},
  {"LIGHT_RWR_ALT_LOW", &panelLEDs[213]},
  {nullptr, nullptr},
  {"LIGHT_CMDS_NO_GO", &panelLEDs[129]},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {"ADI_BUBBLE", &panelLEDs[2]},
  {"SAI_AIRCRAFTREFERENCESYMBOL", &panelLEDs[87]},
  {"LIGHT_ECM_4_S", &panelLEDs[148]},
  {"ADI_PITCH_TRIM", &panelLEDs[10]},
  {"LIGHT_ECM_4_T", &panelLEDs[149]},
  {"COMM1_PWR_KNB", &panelLEDs[26]},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {"LIGHT_CAUTION_1", &panelLEDs[121]},
  {"LIGHT_CAUTION_2", &panelLEDs[122]},
  {"LIGHT_CAUTION_3", &panelLEDs[123]},
  {"LIGHT_CAUTION_4", &panelLEDs[124]},
  {"AIR_REFUEL_LIGHT_KNB", &panelLEDs[52]},
  {"LIGHT_CAUTION_5", &panelLEDs[125]},
  {"ADI_OFF_FLAG", &panelLEDs[8]},
  {"LIGHT_CAUTION_6", &panelLEDs[126]},
  {"TF_KNB", &panelLEDs[33]},
  {nullptr, nullptr},
  {"LIGHT_RWR_MODE_PRI", &panelLEDs[217]},
  {nullptr, nullptr},
  {"FLOOD_CONSOLES_BRT_KNB", &panelLEDs[71]},
  {"ROLL_TRIM", &panelLEDs[43]},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {"LIGHT_RWR_SHIP_UNK", &panelLEDs[222]},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {"LIGHT_CONSLES", &panelLEDs[76]},
  {"ADI_TURNRATE", &panelLEDs[11]},
  {"LIGHT_MARKER_BEACON", &panelLEDs[200]},
  {"LIGHT_RWR_TGTSEP_UP", &panelLEDs[226]},
  {"SPEEDBRAKE_INDICATOR", &panelLEDs[94]},
  {nullptr, nullptr},
  {"CANOPY_LOCK", &panelLEDs[39]},
  {"LIGHT_RWR_MSL_LAUNCH", &panelLEDs[218]},
  {nullptr, nullptr},
  {"ICP_RASTER_CONTR_KNB", &panelLEDs[102]},
  {nullptr, nullptr},
  {"LIGHT_HOOK", &panelLEDs[193]},
  {"STANDBY_COMPASS_PITCH", &panelLEDs[96]},
  {"MAX_AIRSPEED", &panelLEDs[14]},
  {nullptr, nullptr},
  {"FUEL_AL", &panelLEDs[60]},
  {"LIGHT_ECM_SPL_A", &panelLEDs[161]},
  {"OXYGEN_PRESSURE", &panelLEDs[84]},
  {"LIGHT_FL_FAIL", &panelLEDs[185]},
  {"ALT_PRESSURE_DRUM_3_CNT", &panelLEDs[24]},
  {"ALT_1000_FT_CNT", &panelLEDs[17]},
  {"LIGHT_ECM_SPL_F", &panelLEDs[162]},
  {"ADI_GS_FLAG", &panelLEDs[4]},
  {"LIGHT_IFF", &panelLEDs[196]},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {"AOA_INDEX_BRT_KNB", &panelLEDs[69]},
  {"ADI_LOC_FLAG", &panelLEDs[7]},
  {"LIGHT_ECM_1_A", &panelLEDs[134]},
  {nullptr, nullptr},
  {"LIGHT_ECM_SPL_S", &panelLEDs[163]},
  {"LIGHT_ECM_SPL_T", &panelLEDs[164]},
  {"LIGHT_ECM_1_F", &panelLEDs[135]},
  {"ENGINE_TACHOMETER", &panelLEDs[51]},
  {"LIGHT_AIR", &panelLEDs[109]},
  {"LIGHT_FLCS_FAULT", &panelLEDs[178]},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {"SEC_VOICE_KNB", &panelLEDs[31]},
  {"LIGHT_ECM_1_S", &panelLEDs[136]},
  {"LIGHT_ECM_1_T", &panelLEDs[137]},
  {"LIGHT_FUEL_OIL_HOT", &panelLEDs[187]},
  {"SAI_KNB_ARROW", &panelLEDs[90]},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {"LIGHT_INLET_ICING", &panelLEDs[197]},
  {"ICP_HUD_BRT_KNB", &panelLEDs[100]},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {"LIGHT_GEAR_L", &panelLEDs[189]},
  {nullptr, nullptr},
  {"LIGHT_GEAR_N", &panelLEDs[190]},
  {"COCKPIT_ALITITUDE", &panelLEDs[81]},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {"LIGHT_BUC", &panelLEDs[117]},
  {"LIGHT_GEAR_R", &panelLEDs[191]},
  {"LIGHT_STORES_CONFIG", &panelLEDs[231]},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {"LIGHT_ECM_5_A", &panelLEDs[150]},
  {nullptr, nullptr},
  {"PITCHTRIMIND", &panelLEDs[98]},
  {nullptr, nullptr},
  {"LIGHT_RWR_ACTIVITY", &panelLEDs[210]},
  {"LIGHT_ACTIVE", &panelLEDs[107]},
  {"SAI_BANK", &panelLEDs[88]},
  {"SEAT_HEIGHT", &panelLEDs[41]},
  {"LIGHT_ECM_5_F", &panelLEDs[151]},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {"ADI_LOC_BAR", &panelLEDs[6]},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {"LIGHT_ECM_5_S", &panelLEDs[152]},
  {"LIGHT_CANOPY", &panelLEDs[120]},
  {"LIGHT_ECM_5_T", &panelLEDs[153]},
  {"LIGHT_RWR_MODE_OPEN", &panelLEDs[216]},
  {"AR_STATUS_BRT_KNB", &panelLEDs[70]},
  {"UHF_VOL_KNB", &panelLEDs[104]},
  {"LIGHT_TO_LDG_CONFIG", &panelLEDs[234]},
  {"RWR_INTENS_KNB", &panelLEDs[86]},
  {nullptr, nullptr},
  {"ALT_PRESSURE_DRUM_2_CNT", &panelLEDs[23]},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {"ENGINE_FTIT", &panelLEDs[48]},
  {nullptr, nullptr},
  {"LIGHT_RWR_ACT_POWER", &panelLEDs[211]},
  {nullptr, nullptr},
  {"LIGHT_RWR_SYSTEST", &panelLEDs[223]},
  {"FUELTOTALIZER_1K", &panelLEDs[59]},
  {"ADI_GS_POINTER", &panelLEDs[5]},
  {nullptr, nullptr},
  {"LIGHT_OXY_LOW", &panelLEDs[206]},
  {nullptr, nullptr},
  {"MSL_KNB", &panelLEDs[30]},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {"PITCH_TRIM", &panelLEDs[42]},
  {nullptr, nullptr},
  {"SYSA_PRESSURE", &panelLEDs[63]},
  {nullptr, nullptr},
  {"ADI_PITCH", &panelLEDs[9]},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {"STANDBY_COMPASS_HEADING", &panelLEDs[95]},
  {"LIGHT_RADAR_ALT", &panelLEDs[208]},
  {"LIGHT_FLCS_RLY", &panelLEDs[184]},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {"LIGHT_ENG_FIRE", &panelLEDs[172]},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {"HMCS_INT_KNB", &panelLEDs[62]},
  {nullptr, nullptr},
  {"PRI_CONSOLES_BRT_KNB", &panelLEDs[73]},
  {"SET_AIRSPEED", &panelLEDs[15]},
  {"LIGHT_CADC", &panelLEDs[119]},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {"LIGHT_AR_NWS", &panelLEDs[114]},
  {nullptr, nullptr},
  {"COMM2_PWR_KNB", &panelLEDs[27]},
  {"CLOCK_CURRTIME_MS", &panelLEDs[36]},
  {"STANDBY_COMPASS_ROLL", &panelLEDs[97]},
  {"FORM_LIGHT_KNB", &panelLEDs[53]},
  {"LIGHT_RWR_SEARCH", &panelLEDs[220]},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {"LIGHT_RWR_HANDOFF_UP", &panelLEDs[215]},
  {nullptr, nullptr},
  {"LIGHT_ECM_2_A", &panelLEDs[138]},
  {"LIGHT_AVIONICS_FAULT", &panelLEDs[116]},
  {nullptr, nullptr},
  {"SAI_OFF_FLAG", &panelLEDs[91]},
  {"LIGHT_FLCS", &panelLEDs[177]},
  {"LIGHT_ECM_2_F", &panelLEDs[139]},
  {"LIGHT_FLCS_PWR_A", &panelLEDs[180]},
};

// Reuse shared recursive hash implementation
constexpr uint16_t ledHash(const char* s) { return labelHash(s); }

// findLED lookup
inline const LEDMapping* findLED(const char* label) {
  uint16_t startH = ledHash(label) % 479;
  for (uint16_t i = 0; i < 479; ++i) {
    uint16_t idx = (startH + i >= 479) ? (startH + i - 479) : (startH + i);
    const auto& entry = ledHashTable[idx];
    if (!entry.label) continue;
    if (strcmp(entry.label, label) == 0) return entry.led;
  }
  return nullptr;
}
