#define LABEL_SET_NAME        "CABIN_PRESSURE_GAUGE"
#define HAS_HID_MODE_SELECTOR 0
#define MODE_DEFAULT_IS_HID   0
#define LABEL_SET_FULLNAME    "CockpitOS Cabin Pressure Gauge"
#define HAS_CABIN_PRESSURE_GAUGE
