#define LABEL_SET_NAME        "RIGHT_PANEL_CONTROLLER"
#define HAS_HID_MODE_SELECTOR 0
#define MODE_DEFAULT_IS_HID   0
#define LABEL_SET_FULLNAME    "CockpitOS Right Panel Controller"
#define HAS_RIGHT_PANEL_CONTROLLER
