// THIS FILE IS AUTO-GENERATED; ONLY EDIT INDIVIDUAL LED/GAUGE RECORDS, DO NOT ADD OR DELETE THEM HERE
#pragma once

// Embedded LEDMapping structure and enums
enum LEDDeviceType {
  DEVICE_NONE,
  DEVICE_GPIO,
  DEVICE_GAUGE,
  DEVICE_PCA9555,
  DEVICE_GN1640T,
  DEVICE_TM1637,
  DEVICE_WS2812,
};

struct LEDMapping {
  const char* label;
  LEDDeviceType deviceType;
  union {
    struct { uint8_t gpio; } gpioInfo;
    struct { uint8_t gpio; uint16_t minPulse; uint16_t maxPulse; uint16_t period; } gaugeInfo;
    struct { uint8_t address; uint8_t port; uint8_t bit; } pcaInfo;
    struct { uint8_t clkPin; uint8_t dioPin; uint8_t segment; uint8_t bit; } tm1637Info;
    struct { uint8_t address; uint8_t column; uint8_t row; } gn1640Info;
    struct { uint8_t index; } ws2812Info;
  } info;
  bool dimmable;
  bool activeLow;
};

// Auto-generated panelLEDs array
static const LEDMapping panelLEDs[] = {
  { "AMPCD_BRT_CTL"         , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "FIRE_APU_LT"           , DEVICE_TM1637  , {.tm1637Info = {37, 40, 5, 0}}, false, false }, // TM1637 CLK 37 DIO 40 Seg 5 Bit 0,
  { "AOA_INDEXER_HIGH"      , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "AOA_INDEXER_HIGH_F"    , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "AOA_INDEXER_LOW"       , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "AOA_INDEXER_LOW_F"     , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "AOA_INDEXER_NORMAL"    , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "AOA_INDEXER_NORMAL_F"  , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "ARRESTING_HOOK_LT"     , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "APU_READY_LT"          , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "CLIP_APU_ACC_LT"       , DEVICE_GN1640T , {.gn1640Info = {0, 1, 0}}, false, false }, // GN1640 Addr 0 Col 1 Row 0,
  { "CLIP_BATT_SW_LT"       , DEVICE_GN1640T , {.gn1640Info = {0, 2, 0}}, false, false }, // GN1640 Addr 0 Col 2 Row 0,
  { "CLIP_CK_SEAT_LT"       , DEVICE_GN1640T , {.gn1640Info = {0, 0, 0}}, false, false }, // GN1640 Addr 0 Col 0 Row 0,
  { "CLIP_FCES_LT"          , DEVICE_GN1640T , {.gn1640Info = {0, 1, 2}}, false, false }, // GN1640 Addr 0 Col 1 Row 2,
  { "CLIP_FCS_HOT_LT"       , DEVICE_GN1640T , {.gn1640Info = {0, 0, 1}}, false, false }, // GN1640 Addr 0 Col 0 Row 1,
  { "CLIP_FUEL_LO_LT"       , DEVICE_GN1640T , {.gn1640Info = {0, 0, 2}}, false, false }, // GN1640 Addr 0 Col 0 Row 2,
  { "CLIP_GEN_TIE_LT"       , DEVICE_GN1640T , {.gn1640Info = {0, 1, 1}}, false, false }, // GN1640 Addr 0 Col 1 Row 1,
  { "CLIP_L_GEN_LT"         , DEVICE_GN1640T , {.gn1640Info = {0, 0, 3}}, false, false }, // GN1640 Addr 0 Col 0 Row 3,
  { "CLIP_R_GEN_LT"         , DEVICE_GN1640T , {.gn1640Info = {0, 1, 3}}, false, false }, // GN1640 Addr 0 Col 1 Row 3,
  { "CLIP_SPARE_CTN1_LT"    , DEVICE_GN1640T , {.gn1640Info = {0, 2, 1}}, false, false }, // GN1640 Addr 0 Col 2 Row 1,
  { "CLIP_SPARE_CTN2_LT"    , DEVICE_GN1640T , {.gn1640Info = {0, 2, 2}}, false, false }, // GN1640 Addr 0 Col 2 Row 2,
  { "CLIP_SPARE_CTN3_LT"    , DEVICE_GN1640T , {.gn1640Info = {0, 2, 3}}, false, false }, // GN1640 Addr 0 Col 2 Row 3,
  { "CLOCK_ELAPSED_MINUTES" , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "CLOCK_ELAPSED_SECONDS" , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "CLOCK_HOURS"           , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "CLOCK_MINUTES"         , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "PRESSURE_ALT"          , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "COM_AUX"               , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "COM_ICS"               , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "COM_MIDS_A"            , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "COM_MIDS_B"            , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "COM_RWR"               , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "COM_TACAN"             , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "COM_VOX"               , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "COM_WPN"               , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "DEFOG_HANDLE"          , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "CMSD_JET_SEL_L"        , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "VOLT_E"                , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "VOLT_U"                , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "LEFT_LOUVER"           , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "RIGHT_LOUVER"          , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "CABIN_TEMP"            , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "SUIT_TEMP"             , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "FORMATION_DIMMER"      , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "POSITION_DIMMER"       , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "FLP_LG_FLAPS_LT"       , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "FLP_LG_FULL_FLAPS_LT"  , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "FLP_LG_HALF_FLAPS_LT"  , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "FLP_LG_LEFT_GEAR_LT"   , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "FLP_LG_NOSE_GEAR_LT"   , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "FLP_LG_RIGHT_GEAR_LT"  , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "RUD_TRIM"              , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "HUD_AOA_INDEXER"       , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "HUD_BALANCE"           , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "HUD_BLACK_LVL"         , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "HUD_SYM_BRT"           , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "IFEI"                  , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "HYD_IND_LEFT"          , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "HYD_IND_RIGHT"         , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "CHART_DIMMER"          , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "CONSOLES_DIMMER"       , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "FLOOD_DIMMER"          , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "INST_PNL_DIMMER"       , DEVICE_GPIO    , {.gpioInfo = {6}}, true, false }, // GPIO 6,
  { "WARN_CAUTION_DIMMER"   , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "CANOPY_POS"            , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "CHART_INT_LT"          , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "CONSOLE_INT_LT"        , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "EMERG_INSTR_INT_LT"    , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "ENG_INSTR_INT_LT"      , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "FLOOD_INT_LT"          , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "IFEI_BTN_INT_LT"       , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "IFEI_DISP_INT_LT"      , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "INSTR_INT_LT"          , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "NVG_FLOOD_INT_LT"      , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "STBY_COMPASS_INT_LT"   , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "KY58_VOLUME"           , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "LH_ADV_ASPJ_OH"        , DEVICE_TM1637  , {.tm1637Info = {37, 39, 5, 1}}, false, false }, // TM1637 CLK 37 DIO 39 Seg 5 Bit 1,
  { "LH_ADV_GO"             , DEVICE_TM1637  , {.tm1637Info = {37, 39, 0, 0}}, false, false }, // TM1637 CLK 37 DIO 39 Seg 0 Bit 0,
  { "LH_ADV_L_BAR_GREEN"    , DEVICE_TM1637  , {.tm1637Info = {37, 39, 4, 0}}, false, false }, // TM1637 CLK 37 DIO 39 Seg 4 Bit 0,
  { "LH_ADV_L_BAR_RED"      , DEVICE_TM1637  , {.tm1637Info = {37, 39, 3, 0}}, false, false }, // TM1637 CLK 37 DIO 39 Seg 3 Bit 0,
  { "LH_ADV_L_BLEED"        , DEVICE_TM1637  , {.tm1637Info = {37, 39, 1, 0}}, false, false }, // TM1637 CLK 37 DIO 39 Seg 1 Bit 0,
  { "LH_ADV_NO_GO"          , DEVICE_TM1637  , {.tm1637Info = {37, 39, 0, 1}}, false, false }, // TM1637 CLK 37 DIO 39 Seg 0 Bit 1,
  { "LH_ADV_REC"            , DEVICE_TM1637  , {.tm1637Info = {37, 39, 3, 1}}, false, false }, // TM1637 CLK 37 DIO 39 Seg 3 Bit 1,
  { "LH_ADV_R_BLEED"        , DEVICE_TM1637  , {.tm1637Info = {37, 39, 1, 1}}, false, false }, // TM1637 CLK 37 DIO 39 Seg 1 Bit 1,
  { "LH_ADV_SPD_BRK"        , DEVICE_TM1637  , {.tm1637Info = {37, 39, 2, 0}}, false, false }, // TM1637 CLK 37 DIO 39 Seg 2 Bit 0,
  { "LH_ADV_STBY"           , DEVICE_TM1637  , {.tm1637Info = {37, 39, 2, 1}}, false, false }, // TM1637 CLK 37 DIO 39 Seg 2 Bit 1,
  { "LH_ADV_XMIT"           , DEVICE_TM1637  , {.tm1637Info = {37, 39, 4, 1}}, false, false }, // TM1637 CLK 37 DIO 39 Seg 4 Bit 1,
  { "OXY_FLOW"              , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "LANDING_GEAR_HANDLE_LT", DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "LEFT_DDI_BRT_CTL"      , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "LEFT_DDI_CONT_CTL"     , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "FIRE_LEFT_LT"          , DEVICE_TM1637  , {.tm1637Info = {37, 39, 0, 2}}, false, false }, // TM1637 CLK 37 DIO 39 Seg 0 Bit 2,
  { "LS_LOCK"               , DEVICE_WS2812  , {.ws2812Info = {0}}, false, false }, // WS2812 Index 0,
  { "LS_SHOOT"              , DEVICE_WS2812  , {.ws2812Info = {1}}, false, false }, // WS2812 Index 1,
  { "LS_SHOOT_STROBE"       , DEVICE_WS2812  , {.ws2812Info = {2}}, false, false }, // WS2812 Index 2,
  { "HMD_OFF_BRT"           , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "SPIN_LT"               , DEVICE_GPIO    , {.gpioInfo = {34}}, false, false }, // GPIO 34,
  { "MASTER_MODE_AA_LT"     , DEVICE_PCA9555 , {.pcaInfo = {0x5B, 1, 3}}, false, true }, // PCA 0x5B Port 1 Bit 3,
  { "MASTER_MODE_AG_LT"     , DEVICE_PCA9555 , {.pcaInfo = {0x5B, 1, 4}}, false, true }, // PCA 0x5B Port 1 Bit 4,
  { "MC_DISCH"              , DEVICE_PCA9555 , {.pcaInfo = {0x5B, 1, 6}}, false, true }, // PCA 0x5B Port 1 Bit 6,
  { "MC_READY"              , DEVICE_PCA9555 , {.pcaInfo = {0x5B, 1, 5}}, false, true }, // PCA 0x5B Port 1 Bit 5,
  { "MASTER_CAUTION_LT"     , DEVICE_TM1637  , {.tm1637Info = {37, 39, 5, 0}}, false, false }, // TM1637 CLK 37 DIO 39 Seg 5 Bit 0,
  { "RH_ADV_AAA"            , DEVICE_TM1637  , {.tm1637Info = {37, 40, 4, 0}}, false, false }, // TM1637 CLK 37 DIO 40 Seg 4 Bit 0,
  { "RH_ADV_AI"             , DEVICE_TM1637  , {.tm1637Info = {37, 40, 4, 1}}, false, false }, // TM1637 CLK 37 DIO 40 Seg 4 Bit 1,
  { "RH_ADV_CW"             , DEVICE_TM1637  , {.tm1637Info = {37, 40, 5, 1}}, false, false }, // TM1637 CLK 37 DIO 40 Seg 5 Bit 1,
  { "RH_ADV_DISP"           , DEVICE_TM1637  , {.tm1637Info = {37, 40, 0, 0}}, false, false }, // TM1637 CLK 37 DIO 40 Seg 0 Bit 0,
  { "RH_ADV_RCDR_ON"        , DEVICE_TM1637  , {.tm1637Info = {37, 40, 0, 1}}, false, false }, // TM1637 CLK 37 DIO 40 Seg 0 Bit 1,
  { "RH_ADV_SAM"            , DEVICE_TM1637  , {.tm1637Info = {37, 40, 3, 0}}, false, false }, // TM1637 CLK 37 DIO 40 Seg 3 Bit 0,
  { "RH_ADV_SPARE_RH1"      , DEVICE_TM1637  , {.tm1637Info = {37, 40, 1, 1}}, false, false }, // TM1637 CLK 37 DIO 40 Seg 1 Bit 1,
  { "RH_ADV_SPARE_RH2"      , DEVICE_TM1637  , {.tm1637Info = {37, 40, 2, 1}}, false, false }, // TM1637 CLK 37 DIO 40 Seg 2 Bit 1,
  { "RH_ADV_SPARE_RH3"      , DEVICE_TM1637  , {.tm1637Info = {37, 40, 3, 1}}, false, false }, // TM1637 CLK 37 DIO 40 Seg 3 Bit 1,
  { "RH_ADV_SPARE_RH4"      , DEVICE_TM1637  , {.tm1637Info = {37, 40, 1, 0}}, false, false }, // TM1637 CLK 37 DIO 40 Seg 1 Bit 0,
  { "RH_ADV_SPARE_RH5"      , DEVICE_TM1637  , {.tm1637Info = {37, 40, 2, 0}}, false, false }, // TM1637 CLK 37 DIO 40 Seg 2 Bit 0,
  { "RWR_AUDIO_CTRL"        , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "RWR_BIT_LT"            , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "RWR_DISPLAY_LT"        , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "RWR_DMR_CTRL"          , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "RWR_ENABLE_LT"         , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "RWR_FAIL_LT"           , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "RWR_LIMIT_LT"          , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "RWR_LOWER_LT"          , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "RWR_LT_BRIGHT"         , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "RWR_OFFSET_LT"         , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "RWR_RWR_INTESITY"      , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "RWR_SPECIAL_EN_LT"     , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "RWR_SPECIAL_LT"        , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "LOW_ALT_WARN_LT"       , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "RADALT_ALT_PTR"        , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "RADALT_GREEN_LAMP"     , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "RADALT_MIN_HEIGHT_PTR" , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "RADALT_OFF_FLAG"       , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "RIGHT_DDI_BRT_CTL"     , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "RIGHT_DDI_CONT_CTL"    , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "FIRE_RIGHT_LT"         , DEVICE_TM1637  , {.tm1637Info = {37, 40, 0, 2}}, false, false }, // TM1637 CLK 37 DIO 40 Seg 0 Bit 2,
  { "HYD_IND_BRAKE"         , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "STBY_ASI_AIRSPEED"     , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "STBY_ALT_10000_FT_CNT" , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "STBY_ALT_1000_FT_CNT"  , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "STBY_ALT_100_FT_PTR"   , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "STBY_PRESS_SET_0"      , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "STBY_PRESS_SET_1"      , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "STBY_PRESS_SET_2"      , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "SAI_ATT_WARNING_FLAG"  , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "SAI_ATT_WARN_FLAG_L"   , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "SAI_BANK"              , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "SAI_MAN_PITCH_ADJ"     , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "SAI_PITCH"             , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "SAI_POINTER_HOR"       , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "SAI_POINTER_VER"       , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "SAI_RATE_OF_TURN"      , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "SAI_SLIP_BALL"         , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "SBY_COMPASS_BANK"      , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "SBY_COMPASS_HDG"       , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "SBY_COMPASS_PITCH"     , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "VSI"                   , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "SJ_CTR_LT"             , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "SJ_LI_LT"              , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "SJ_LO_LT"              , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "SJ_RI_LT"              , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "SJ_RO_LT"              , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "INT_THROTTLE_LEFT"     , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "INT_THROTTLE_RIGHT"    , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "THROTTLE_FRICTION"     , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "THROTTLE_RADAR_ELEV"   , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "UFC_BRT"               , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "UFC_COMM1_VOL"         , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info,
  { "UFC_COMM2_VOL"         , DEVICE_NONE    , {.gpioInfo = {0}}, false, false }, // No Info
};

static constexpr uint16_t panelLEDsCount = sizeof(panelLEDs)/sizeof(panelLEDs[0]);

// Auto-generated hash table
struct LEDHashEntry { const char* label; const LEDMapping* led; };
static const LEDHashEntry ledHashTable[337] = {
  {nullptr, nullptr},
  {nullptr, nullptr},
  {"RH_ADV_SPARE_RH1", &panelLEDs[108]},
  {"RH_ADV_SPARE_RH2", &panelLEDs[109]},
  {"RH_ADV_SPARE_RH3", &panelLEDs[110]},
  {"AOA_INDEXER_HIGH", &panelLEDs[2]},
  {"RH_ADV_SPARE_RH4", &panelLEDs[111]},
  {"RH_ADV_SPARE_RH5", &panelLEDs[112]},
  {"CANOPY_POS", &panelLEDs[64]},
  {"THROTTLE_FRICTION", &panelLEDs[162]},
  {"RH_ADV_RCDR_ON", &panelLEDs[106]},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {"CLIP_BATT_SW_LT", &panelLEDs[11]},
  {"CLIP_GEN_TIE_LT", &panelLEDs[16]},
  {"LS_SHOOT", &panelLEDs[93]},
  {nullptr, nullptr},
  {"STBY_PRESS_SET_0", &panelLEDs[139]},
  {"STBY_PRESS_SET_1", &panelLEDs[140]},
  {"STBY_PRESS_SET_2", &panelLEDs[141]},
  {"SBY_COMPASS_HDG", &panelLEDs[152]},
  {nullptr, nullptr},
  {"RUD_TRIM", &panelLEDs[51]},
  {"CLIP_SPARE_CTN2_LT", &panelLEDs[20]},
  {"RH_ADV_AI", &panelLEDs[103]},
  {"FLP_LG_LEFT_GEAR_LT", &panelLEDs[48]},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {"SAI_BANK", &panelLEDs[144]},
  {"AOA_INDEXER_LOW", &panelLEDs[4]},
  {"MASTER_MODE_AG_LT", &panelLEDs[98]},
  {"CLIP_FUEL_LO_LT", &panelLEDs[15]},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {"INT_THROTTLE_RIGHT", &panelLEDs[161]},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {"INSTR_INT_LT", &panelLEDs[72]},
  {"LEFT_DDI_CONT_CTL", &panelLEDs[90]},
  {"IFEI", &panelLEDs[56]},
  {"FLOOD_DIMMER", &panelLEDs[61]},
  {"RADALT_OFF_FLAG", &panelLEDs[130]},
  {nullptr, nullptr},
  {"UFC_COMM1_VOL", &panelLEDs[165]},
  {"RIGHT_DDI_BRT_CTL", &panelLEDs[131]},
  {"AMPCD_BRT_CTL", &panelLEDs[0]},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {"SBY_COMPASS_PITCH", &panelLEDs[153]},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {"PRESSURE_ALT", &panelLEDs[26]},
  {nullptr, nullptr},
  {"CONSOLES_DIMMER", &panelLEDs[60]},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {"RH_ADV_DISP", &panelLEDs[105]},
  {"UFC_COMM2_VOL", &panelLEDs[166]},
  {"HYD_IND_LEFT", &panelLEDs[57]},
  {"VSI", &panelLEDs[154]},
  {"FLP_LG_RIGHT_GEAR_LT", &panelLEDs[50]},
  {"LS_LOCK", &panelLEDs[92]},
  {"RWR_AUDIO_CTRL", &panelLEDs[113]},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {"CABIN_TEMP", &panelLEDs[41]},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {"CLIP_FCES_LT", &panelLEDs[13]},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {"FLP_LG_FLAPS_LT", &panelLEDs[45]},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {"SAI_RATE_OF_TURN", &panelLEDs[149]},
  {"STBY_ALT_1000_FT_CNT", &panelLEDs[137]},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {"MASTER_MODE_AA_LT", &panelLEDs[97]},
  {"HMD_OFF_BRT", &panelLEDs[95]},
  {"RWR_BIT_LT", &panelLEDs[114]},
  {nullptr, nullptr},
  {"LH_ADV_REC", &panelLEDs[82]},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {"NVG_FLOOD_INT_LT", &panelLEDs[73]},
  {"RH_ADV_CW", &panelLEDs[104]},
  {"SAI_SLIP_BALL", &panelLEDs[150]},
  {"INT_THROTTLE_LEFT", &panelLEDs[160]},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {"WARN_CAUTION_DIMMER", &panelLEDs[63]},
  {"RH_ADV_AAA", &panelLEDs[102]},
  {nullptr, nullptr},
  {"CLOCK_HOURS", &panelLEDs[24]},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {"AOA_INDEXER_NORMAL_F", &panelLEDs[7]},
  {"RWR_LT_BRIGHT", &panelLEDs[121]},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {"COM_AUX", &panelLEDs[27]},
  {"VOLT_E", &panelLEDs[37]},
  {"LH_ADV_ASPJ_OH", &panelLEDs[76]},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {"RWR_DISPLAY_LT", &panelLEDs[115]},
  {"FIRE_APU_LT", &panelLEDs[1]},
  {"INST_PNL_DIMMER", &panelLEDs[62]},
  {"CLOCK_ELAPSED_MINUTES", &panelLEDs[22]},
  {nullptr, nullptr},
  {"MC_DISCH", &panelLEDs[99]},
  {nullptr, nullptr},
  {"LH_ADV_L_BAR_GREEN", &panelLEDs[78]},
  {"IFEI_DISP_INT_LT", &panelLEDs[71]},
  {"FLP_LG_NOSE_GEAR_LT", &panelLEDs[49]},
  {"CLIP_SPARE_CTN1_LT", &panelLEDs[19]},
  {"OXY_FLOW", &panelLEDs[87]},
  {"VOLT_U", &panelLEDs[38]},
  {"LH_ADV_SPD_BRK", &panelLEDs[84]},
  {"RIGHT_LOUVER", &panelLEDs[40]},
  {"RWR_DMR_CTRL", &panelLEDs[116]},
  {"RWR_RWR_INTESITY", &panelLEDs[123]},
  {"HYD_IND_BRAKE", &panelLEDs[134]},
  {"CLOCK_ELAPSED_SECONDS", &panelLEDs[23]},
  {"SJ_LO_LT", &panelLEDs[157]},
  {"COM_ICS", &panelLEDs[28]},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {"COM_MIDS_A", &panelLEDs[29]},
  {"COM_MIDS_B", &panelLEDs[30]},
  {"RWR_LIMIT_LT", &panelLEDs[119]},
  {"STBY_ALT_100_FT_PTR", &panelLEDs[138]},
  {"HUD_BLACK_LVL", &panelLEDs[54]},
  {nullptr, nullptr},
  {"SUIT_TEMP", &panelLEDs[42]},
  {nullptr, nullptr},
  {"COM_RWR", &panelLEDs[31]},
  {"CHART_DIMMER", &panelLEDs[59]},
  {nullptr, nullptr},
  {"THROTTLE_RADAR_ELEV", &panelLEDs[163]},
  {nullptr, nullptr},
  {"RIGHT_DDI_CONT_CTL", &panelLEDs[132]},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {"DEFOG_HANDLE", &panelLEDs[35]},
  {"RH_ADV_SAM", &panelLEDs[107]},
  {"RWR_SPECIAL_LT", &panelLEDs[125]},
  {"MASTER_CAUTION_LT", &panelLEDs[101]},
  {nullptr, nullptr},
  {"POSITION_DIMMER", &panelLEDs[44]},
  {nullptr, nullptr},
  {"FLOOD_INT_LT", &panelLEDs[69]},
  {"CLIP_FCS_HOT_LT", &panelLEDs[14]},
  {"CLOCK_MINUTES", &panelLEDs[25]},
  {"CLIP_APU_ACC_LT", &panelLEDs[10]},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {"FIRE_LEFT_LT", &panelLEDs[91]},
  {"RWR_OFFSET_LT", &panelLEDs[122]},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {"HUD_BALANCE", &panelLEDs[53]},
  {"LH_ADV_NO_GO", &panelLEDs[81]},
  {"STBY_ASI_AIRSPEED", &panelLEDs[135]},
  {nullptr, nullptr},
  {"FLP_LG_FULL_FLAPS_LT", &panelLEDs[46]},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {"MC_READY", &panelLEDs[100]},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {"SJ_LI_LT", &panelLEDs[156]},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {"CMSD_JET_SEL_L", &panelLEDs[36]},
  {"STBY_COMPASS_INT_LT", &panelLEDs[74]},
  {"RWR_LOWER_LT", &panelLEDs[120]},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {"HUD_SYM_BRT", &panelLEDs[55]},
  {"IFEI_BTN_INT_LT", &panelLEDs[70]},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {"FORMATION_DIMMER", &panelLEDs[43]},
  {"AOA_INDEXER_HIGH_F", &panelLEDs[3]},
  {"ARRESTING_HOOK_LT", &panelLEDs[8]},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {"COM_VOX", &panelLEDs[33]},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {"AOA_INDEXER_LOW_F", &panelLEDs[5]},
  {nullptr, nullptr},
  {"LOW_ALT_WARN_LT", &panelLEDs[126]},
  {nullptr, nullptr},
  {"SAI_POINTER_HOR", &panelLEDs[147]},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {"HYD_IND_RIGHT", &panelLEDs[58]},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {"CLIP_SPARE_CTN3_LT", &panelLEDs[21]},
  {"FLP_LG_HALF_FLAPS_LT", &panelLEDs[47]},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {"LEFT_LOUVER", &panelLEDs[39]},
  {nullptr, nullptr},
  {"APU_READY_LT", &panelLEDs[9]},
  {"HUD_AOA_INDEXER", &panelLEDs[52]},
  {"LH_ADV_STBY", &panelLEDs[85]},
  {nullptr, nullptr},
  {"LANDING_GEAR_HANDLE_LT", &panelLEDs[88]},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {"CLIP_R_GEN_LT", &panelLEDs[18]},
  {"SJ_RO_LT", &panelLEDs[159]},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {"ENG_INSTR_INT_LT", &panelLEDs[68]},
  {"CONSOLE_INT_LT", &panelLEDs[66]},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {"SAI_ATT_WARNING_FLAG", &panelLEDs[142]},
  {nullptr, nullptr},
  {"KY58_VOLUME", &panelLEDs[75]},
  {"RWR_FAIL_LT", &panelLEDs[118]},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {"SAI_MAN_PITCH_ADJ", &panelLEDs[145]},
  {"AOA_INDEXER_NORMAL", &panelLEDs[6]},
  {"SPIN_LT", &panelLEDs[96]},
  {"FIRE_RIGHT_LT", &panelLEDs[133]},
  {"SAI_ATT_WARN_FLAG_L", &panelLEDs[143]},
  {nullptr, nullptr},
  {"SBY_COMPASS_BANK", &panelLEDs[151]},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {"RWR_ENABLE_LT", &panelLEDs[117]},
  {"CLIP_CK_SEAT_LT", &panelLEDs[12]},
  {nullptr, nullptr},
  {"LEFT_DDI_BRT_CTL", &panelLEDs[89]},
  {nullptr, nullptr},
  {"RWR_SPECIAL_EN_LT", &panelLEDs[124]},
  {"CLIP_L_GEN_LT", &panelLEDs[17]},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {"EMERG_INSTR_INT_LT", &panelLEDs[67]},
  {"SAI_PITCH", &panelLEDs[146]},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {"LH_ADV_R_BLEED", &panelLEDs[83]},
  {"LH_ADV_L_BLEED", &panelLEDs[80]},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {"LH_ADV_L_BAR_RED", &panelLEDs[79]},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {"LH_ADV_GO", &panelLEDs[77]},
  {"CHART_INT_LT", &panelLEDs[65]},
  {"COM_TACAN", &panelLEDs[32]},
  {"RADALT_ALT_PTR", &panelLEDs[127]},
  {"RADALT_GREEN_LAMP", &panelLEDs[128]},
  {"STBY_ALT_10000_FT_CNT", &panelLEDs[136]},
  {"UFC_BRT", &panelLEDs[164]},
  {"SJ_RI_LT", &panelLEDs[158]},
  {"RADALT_MIN_HEIGHT_PTR", &panelLEDs[129]},
  {nullptr, nullptr},
  {"SJ_CTR_LT", &panelLEDs[155]},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {"SAI_POINTER_VER", &panelLEDs[148]},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {"COM_WPN", &panelLEDs[34]},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {"LH_ADV_XMIT", &panelLEDs[86]},
  {"LS_SHOOT_STROBE", &panelLEDs[94]},
};

// Reuse shared recursive hash implementation
constexpr uint16_t ledHash(const char* s) { return labelHash(s); }

// findLED lookup
inline const LEDMapping* findLED(const char* label) {
  uint16_t startH = ledHash(label) % 337;
  for (uint16_t i = 0; i < 337; ++i) {
    uint16_t idx = (startH + i >= 337) ? (startH + i - 337) : (startH + i);
    const auto& entry = ledHashTable[idx];
    if (!entry.label) continue;
    if (strcmp(entry.label, label) == 0) return entry.led;
  }
  return nullptr;
}
