#!/usr/bin/env python3
"""
CockpitOS Reset Data Wrapper
============================
Thin wrapper - all logic lives in ../_core/reset_core.py
DO NOT EDIT THIS FILE - edit the core module instead.
"""
import os, sys
os.chdir(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..', '_core'))
from reset_core import run
run()
