// THIS FILE IS AUTO-GENERATED; ONLY EDIT INDIVIDUAL RECORDS, DO NOT ADD OR DELETE THEM HERE
// You can use a PIN(X) macro where X is an S2 PIN to AUTO-CONVERT to its equivalent position in an S3 device.
// So, PIN(4) will always be PIN 4 if you compile with an S2 but will get automatically converted to 5 if you compile the firmware on an S3.
// This is to easily use S2 or S3 devices on same backplane/hardware physically connected to specific PINs
#pragma once

struct InputMapping {
    const char* label;        // Unique selector label, auto-generated.
    const char* source;      // Hardware source identifier. (e.g PCA_0x26, HC165, GPIO, NONE etc)
    int8_t     port;           // Port index (For PCA use port 0 or 1, HC165 does not use port. For GPIO use PIN and use -1 when sharing GPIOs to differentiate HIGH/LOW)
    int8_t     bit;            // Bit position is used for PCA & HC165. GPIO also uses it but ONLY for one-hot selectors (GPIO assigned for each position) in such cases set as -1
    int8_t      hidId;        // HID usage ID
    const char* oride_label;  // Override command label (dcsCommand)
    uint16_t    oride_value;  // Override command value (value)
    const char* controlType;  // Control type, e.g., "selector"
    uint16_t    group;        // Group ID for exclusive selectors
};

//  label                       source     port bit hidId  DCSCommand           value   Type        group
static const InputMapping InputMappings[] = {
    { "DEFOG_HANDLE"                , "GPIO" , PIN(15) ,  0 ,  -1 , "DEFOG_HANDLE"          , 65535 , "analog"       ,  0 },
    { "DEFOG_HANDLE_DEC"            , "NONE" ,  0 ,  0 ,  -1 , "DEFOG_HANDLE"          ,     0 , "variable_step",  0 },
    { "DEFOG_HANDLE_INC"            , "NONE" ,  0 ,  0 ,  -1 , "DEFOG_HANDLE"          ,     1 , "variable_step",  0 },
    { "WSHIELD_ANTI_ICE_SW_RAIN"    , "HC165" ,  0 , 30 ,  -1 , "WSHIELD_ANTI_ICE_SW"   ,     0 , "selector"     , 22 },
    { "WSHIELD_ANTI_ICE_SW_OFF"     , "HC165" ,  0 , -1 ,  -1 , "WSHIELD_ANTI_ICE_SW"   ,     1 , "selector"     , 22 },
    { "WSHIELD_ANTI_ICE_SW_ANTI_ICE", "HC165" ,  0 , 31 ,  -1 , "WSHIELD_ANTI_ICE_SW"   ,     2 , "selector"     , 22 },
    { "BATTERY_SW_ORIDE"            , "HC165" ,  0 , 32 ,  -1 , "BATTERY_SW"            ,     0 , "selector"     ,  1 },
    { "BATTERY_SW_OFF"              , "HC165" ,  0 , -1 ,  -1 , "BATTERY_SW"            ,     1 , "selector"     ,  1 },
    { "BATTERY_SW_ON"               , "HC165" ,  0 , 33 ,  -1 , "BATTERY_SW"            ,     2 , "selector"     ,  1 },
    { "L_GEN_SW_OFF"                , "HC165" ,  0 , 34 ,  -1 , "L_GEN_SW"              ,     0 , "selector"     ,  2 },
    { "L_GEN_SW_NORM"               , "HC165" ,  0 , -1 ,  -1 , "L_GEN_SW"              ,     1 , "selector"     ,  2 },
    { "R_GEN_SW_OFF"                , "HC165" ,  0 , 35 ,  -1 , "R_GEN_SW"              ,     0 , "selector"     ,  3 },
    { "R_GEN_SW_NORM"               , "HC165" ,  0 , -1 ,  -1 , "R_GEN_SW"              ,     1 , "selector"     ,  3 },
    { "BLEED_AIR_KNOB_OFF"          , "GPIO" , PIN(37) , -1 ,  -1 , "BLEED_AIR_KNOB"        ,     0 , "selector"     ,  8 },
    { "BLEED_AIR_KNOB_L_OFF"        , "GPIO" , PIN(38) , -1 ,  -1 , "BLEED_AIR_KNOB"        ,     1 , "selector"     ,  8 },
    { "BLEED_AIR_KNOB_NORM"         , "GPIO" , PIN(39) , -1 ,  -1 , "BLEED_AIR_KNOB"        ,     2 , "selector"     ,  8 },
    { "BLEED_AIR_KNOB_R_OFF"        , "GPIO" , PIN(40) , -1 ,  -1 , "BLEED_AIR_KNOB"        ,     3 , "selector"     ,  8 },
    { "BLEED_AIR_KNOB_DEC"          , "NONE" ,  0 ,  0 ,  -1 , "BLEED_AIR_KNOB"        ,     0 , "fixed_step"   ,  0 },
    { "BLEED_AIR_KNOB_INC"          , "NONE" ,  0 ,  0 ,  -1 , "BLEED_AIR_KNOB"        ,     1 , "fixed_step"   ,  0 },
    { "BLEED_AIR_PULL_POS0"         , "NONE" ,  0 ,  0 ,  -1 , "BLEED_AIR_PULL"        ,     0 , "selector"     ,  0 },
    { "BLEED_AIR_PULL_POS1"         , "NONE" ,  0 ,  0 ,  -1 , "BLEED_AIR_PULL"        ,     1 , "selector"     ,  0 },
    { "CABIN_PRESS_SW_POS0"         , "HC165" ,  0 , 40 ,  -1 , "CABIN_PRESS_SW"        ,     0 , "selector"     ,  4 },
    { "CABIN_PRESS_SW_POS1"         , "HC165" ,  0 , -1 ,  -1 , "CABIN_PRESS_SW"        ,     1 , "selector"     ,  4 },
    { "CABIN_PRESS_SW_POS2"         , "HC165" ,  0 , 46 ,  -1 , "CABIN_PRESS_SW"        ,     2 , "selector"     ,  4 },
    { "CABIN_TEMP"                  , "GPIO" , PIN(3) ,  0 ,  -1 , "CABIN_TEMP"            , 65535 , "analog"       ,  0 },
    { "CABIN_TEMP_DEC"              , "NONE" ,  0 ,  0 ,  -1 , "CABIN_TEMP"            ,     0 , "variable_step",  0 },
    { "CABIN_TEMP_INC"              , "NONE" ,  0 ,  0 ,  -1 , "CABIN_TEMP"            ,     1 , "variable_step",  0 },
    { "ECS_MODE_SW_POS0"            , "HC165" ,  0 , 43 ,  -1 , "ECS_MODE_SW"           ,     0 , "selector"     ,  7 },
    { "ECS_MODE_SW_POS1"            , "HC165" ,  0 , -1 ,  -1 , "ECS_MODE_SW"           ,     1 , "selector"     ,  7 },
    { "ECS_MODE_SW_POS2"            , "HC165" ,  0 , 44 ,  -1 , "ECS_MODE_SW"           ,     2 , "selector"     ,  7 },
    { "ENG_ANTIICE_SW_TEST"         , "HC165" ,  0 , 42 ,  -1 , "ENG_ANTIICE_SW"        ,     0 , "selector"     ,  6 },
    { "ENG_ANTIICE_SW_OFF"          , "HC165" ,  0 , -1 ,  -1 , "ENG_ANTIICE_SW"        ,     1 , "selector"     ,  6 },
    { "ENG_ANTIICE_SW_ON"           , "HC165" ,  0 , 41 ,  -1 , "ENG_ANTIICE_SW"        ,     2 , "selector"     ,  6 },
    { "PITOT_HEAT_SW_AUTO"          , "HC165" ,  0 , 45 ,  -1 , "PITOT_HEAT_SW"         ,     0 , "selector"     , 21 },
    { "PITOT_HEAT_SW_ON"            , "HC165" ,  0 , -1 ,  -1 , "PITOT_HEAT_SW"         ,     1 , "selector"     , 21 },
    { "SUIT_TEMP"                   , "GPIO" , PIN(4) ,  0 ,  -1 , "SUIT_TEMP"             , 65535 , "analog"       ,  0 },
    { "SUIT_TEMP_DEC"               , "NONE" ,  0 ,  0 ,  -1 , "SUIT_TEMP"             ,     0 , "variable_step",  0 },
    { "SUIT_TEMP_INC"               , "NONE" ,  0 ,  0 ,  -1 , "SUIT_TEMP"             ,     1 , "variable_step",  0 },
    { "CHART_DIMMER"                , "GPIO" , PIN(7) ,  0 ,  -1 , "CHART_DIMMER"          , 65535 , "analog"       ,  0 },
    { "CHART_DIMMER_DEC"            , "NONE" ,  0 ,  0 ,  -1 , "CHART_DIMMER"          ,     0 , "variable_step",  0 },
    { "CHART_DIMMER_INC"            , "NONE" ,  0 ,  0 ,  -1 , "CHART_DIMMER"          ,     1 , "variable_step",  0 },
    { "COCKKPIT_LIGHT_MODE_SW_DAY"  , "HC165" ,  0 , 36 ,  -1 , "COCKKPIT_LIGHT_MODE_SW",     0 , "selector"     , 15 },
    { "COCKKPIT_LIGHT_MODE_SW_NITE" , "HC165" ,  0 , -1 ,  -1 , "COCKKPIT_LIGHT_MODE_SW",     1 , "selector"     , 15 },
    { "COCKKPIT_LIGHT_MODE_SW_NVG"  , "HC165" ,  0 , 37 ,  -1 , "COCKKPIT_LIGHT_MODE_SW",     2 , "selector"     , 15 },
    { "CONSOLES_DIMMER"             , "GPIO" , PIN(5) ,  0 ,  -1 , "CONSOLES_DIMMER"       , 65535 , "analog"       ,  0 },
    { "CONSOLES_DIMMER_DEC"         , "NONE" ,  0 ,  0 ,  -1 , "CONSOLES_DIMMER"       ,     0 , "variable_step",  0 },
    { "CONSOLES_DIMMER_INC"         , "NONE" ,  0 ,  0 ,  -1 , "CONSOLES_DIMMER"       ,     1 , "variable_step",  0 },
    { "FLOOD_DIMMER"                , "GPIO" , PIN(1) ,  0 ,  -1 , "FLOOD_DIMMER"          , 65535 , "analog"       ,  0 },
    { "FLOOD_DIMMER_DEC"            , "NONE" ,  0 ,  0 ,  -1 , "FLOOD_DIMMER"          ,     0 , "variable_step",  0 },
    { "FLOOD_DIMMER_INC"            , "NONE" ,  0 ,  0 ,  -1 , "FLOOD_DIMMER"          ,     1 , "variable_step",  0 },
    { "INST_PNL_DIMMER"             , "GPIO" , PIN(2) ,  0 ,  -1 , "INST_PNL_DIMMER"       , 65535 , "analog"       ,  0 },
    { "INST_PNL_DIMMER_DEC"         , "NONE" ,  0 ,  0 ,  -1 , "INST_PNL_DIMMER"       ,     0 , "variable_step",  0 },
    { "INST_PNL_DIMMER_INC"         , "NONE" ,  0 ,  0 ,  -1 , "INST_PNL_DIMMER"       ,     1 , "variable_step",  0 },
    { "LIGHTS_TEST_SW_OFF"          , "HC165" ,  0 , -1 ,  -1 , "LIGHTS_TEST_SW"        ,     0 , "selector"     , 14 },
    { "LIGHTS_TEST_SW_TEST"         , "HC165" ,  0 , 38 ,  -1 , "LIGHTS_TEST_SW"        ,     1 , "selector"     , 14 },
    { "WARN_CAUTION_DIMMER"         , "GPIO" , PIN(6) ,  0 ,  -1 , "WARN_CAUTION_DIMMER"   , 65535 , "analog"       ,  0 },
    { "WARN_CAUTION_DIMMER_DEC"     , "NONE" ,  0 ,  0 ,  -1 , "WARN_CAUTION_DIMMER"   ,     0 , "variable_step",  0 },
    { "WARN_CAUTION_DIMMER_INC"     , "NONE" ,  0 ,  0 ,  -1 , "WARN_CAUTION_DIMMER"   ,     1 , "variable_step",  0 },
    { "CANOPY_SW_CLOSE"             , "HC165" ,  0 , 24 ,  -1 , "CANOPY_SW"             ,     0 , "selector"     , 23 },
    { "CANOPY_SW_HOLD"              , "HC165" ,  0 , -1 ,  -1 , "CANOPY_SW"             ,     1 , "selector"     , 23 },
    { "CANOPY_SW_OPEN"              , "HC165" ,  0 , 39 ,  -1 , "CANOPY_SW"             ,     2 , "selector"     , 23 },
    { "CB_FCS_CHAN3"                , "NONE" ,  0 ,  0 ,  -1 , "CB_FCS_CHAN3"          ,     1 , "momentary"    ,  0 },
    { "CB_FCS_CHAN4"                , "NONE" ,  0 ,  0 ,  -1 , "CB_FCS_CHAN4"          ,     1 , "momentary"    ,  0 },
    { "CB_HOOOK"                    , "NONE" ,  0 ,  0 ,  -1 , "CB_HOOOK"              ,     1 , "momentary"    ,  0 },
    { "CB_LG"                       , "NONE" ,  0 ,  0 ,  -1 , "CB_LG"                 ,     1 , "momentary"    ,  0 },
    { "FCS_BIT_SW_PRESS"            , "HC165" ,  0 , -1 ,  -1 , "FCS_BIT_SW"            ,     0 , "selector"     , 27 },
    { "FCS_BIT_SW_RELEASE"          , "HC165" ,  0 ,  4 ,  -1 , "FCS_BIT_SW"            ,     1 , "selector"     , 27 },
    { "FLIR_SW_OFF"                 , "HC165" ,  0 , 26 ,  -1 , "FLIR_SW"               ,     0 , "selector"     , 16 },
    { "FLIR_SW_STBY"                , "HC165" ,  0 , -1 ,  -1 , "FLIR_SW"               ,     1 , "selector"     , 16 },
    { "FLIR_SW_ON"                  , "HC165" ,  0 , 25 ,  -1 , "FLIR_SW"               ,     2 , "selector"     , 16 },
    { "INS_SW_TEST"                 , "HC165" ,  0 , 23 ,  -1 , "INS_SW"                ,     7 , "selector"     , 20 },
    { "INS_SW_GB"                   , "HC165" ,  0 , 22 ,  -1 , "INS_SW"                ,     6 , "selector"     , 20 },
    { "INS_SW_GYRO"                 , "HC165" ,  0 , 21 ,  -1 , "INS_SW"                ,     5 , "selector"     , 20 },
    { "INS_SW_IFA"                  , "HC165" ,  0 , 20 ,  -1 , "INS_SW"                ,     4 , "selector"     , 20 },
    { "INS_SW_NAV"                  , "HC165" ,  0 , 19 ,  -1 , "INS_SW"                ,     3 , "selector"     , 20 },
    { "INS_SW_GND"                  , "HC165" ,  0 , 18 ,  -1 , "INS_SW"                ,     2 , "selector"     , 20 },
    { "INS_SW_CV"                   , "HC165" ,  0 , 17 ,  -1 , "INS_SW"                ,     1 , "selector"     , 20 },
    { "INS_SW_OFF"                  , "HC165" ,  0 , 16 ,  -1 , "INS_SW"                ,     0 , "selector"     , 20 },
    { "INS_SW_DEC"                  , "NONE" ,  0 ,  0 ,  -1 , "INS_SW"                ,     0 , "fixed_step"   ,  0 },
    { "INS_SW_INC"                  , "NONE" ,  0 ,  0 ,  -1 , "INS_SW"                ,     1 , "fixed_step"   ,  0 },
    { "LST_NFLR_SW_OFF"             , "HC165" ,  0 , 29 ,  -1 , "LST_NFLR_SW"           ,     0 , "selector"     , 19 },
    { "LST_NFLR_SW_ON"              , "HC165" ,  0 , -1 ,  -1 , "LST_NFLR_SW"           ,     1 , "selector"     , 19 },
    { "LTD_R_SW_SAFE"               , "HC165" ,  0 , -1 ,  -1 , "LTD_R_SW"              ,     0 , "selector"     , 28 },
    { "LTD_R_SW_ARM"                , "HC165" ,  0 , 28 ,  -1 , "LTD_R_SW"              ,     1 , "selector"     , 28 },
    { "RADAR_SW_EMERG(PULL)"        , "HC165" ,  0 , 11 ,  -1 , "RADAR_SW"              ,     3 , "selector"     , 17 },
    { "RADAR_SW_OPR"                , "HC165" ,  0 , 10 ,  -1 , "RADAR_SW"              ,     2 , "selector"     , 17 },
    { "RADAR_SW_STBY"               , "HC165" ,  0 ,  9 ,  -1 , "RADAR_SW"              ,     1 , "selector"     , 17 },
    { "RADAR_SW_OFF"                , "HC165" ,  0 ,  8 ,  -1 , "RADAR_SW"              ,     0 , "selector"     , 17 },
    { "RADAR_SW_DEC"                , "NONE" ,  0 ,  0 ,  -1 , "RADAR_SW"              ,     0 , "fixed_step"   ,  0 },
    { "RADAR_SW_INC"                , "NONE" ,  0 ,  0 ,  -1 , "RADAR_SW"              ,     1 , "fixed_step"   ,  0 },
    { "RADAR_SW_PULL"               , "NONE" ,  0 ,  0 ,  -1 , "RADAR_SW_PULL"         ,     1 , "momentary"    ,  0 },
};
static const size_t InputMappingSize = sizeof(InputMappings)/sizeof(InputMappings[0]);

// Auto-generated: selector DCS labels with group > 0 (panel sync)
static const char* const TrackedSelectorLabels[] = {
    "BATTERY_SW",
    "BLEED_AIR_KNOB",
    "CABIN_PRESS_SW",
    "CANOPY_SW",
    "COCKKPIT_LIGHT_MODE_SW",
    "ECS_MODE_SW",
    "ENG_ANTIICE_SW",
    "FCS_BIT_SW",
    "FLIR_SW",
    "INS_SW",
    "LIGHTS_TEST_SW",
    "LST_NFLR_SW",
    "LTD_R_SW",
    "L_GEN_SW",
    "PITOT_HEAT_SW",
    "RADAR_SW",
    "R_GEN_SW",
    "WSHIELD_ANTI_ICE_SW",
};
static const size_t TrackedSelectorLabelsCount = sizeof(TrackedSelectorLabels)/sizeof(TrackedSelectorLabels[0]);


// Static hash lookup table for InputMappings[]
struct InputHashEntry { const char* label; const InputMapping* mapping; };
static const InputHashEntry inputHashTable[191] = {
  {nullptr, nullptr},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {"DEFOG_HANDLE_DEC", &InputMappings[1]},
  {"CB_FCS_CHAN3", &InputMappings[61]},
  {"CB_FCS_CHAN4", &InputMappings[62]},
  {nullptr, nullptr},
  {"LTD_R_SW_SAFE", &InputMappings[82]},
  {"PITOT_HEAT_SW_AUTO", &InputMappings[33]},
  {"BLEED_AIR_PULL_POS0", &InputMappings[19]},
  {"BLEED_AIR_PULL_POS1", &InputMappings[20]},
  {"INST_PNL_DIMMER_DEC", &InputMappings[51]},
  {"ENG_ANTIICE_SW_TEST", &InputMappings[30]},
  {"INS_SW_CV", &InputMappings[76]},
  {"RADAR_SW_OFF", &InputMappings[87]},
  {"DEFOG_HANDLE_INC", &InputMappings[2]},
  {"WARN_CAUTION_DIMMER_DEC", &InputMappings[56]},
  {nullptr, nullptr},
  {"FCS_BIT_SW_PRESS", &InputMappings[65]},
  {"PITOT_HEAT_SW_ON", &InputMappings[34]},
  {"INS_SW_OFF", &InputMappings[77]},
  {"FLIR_SW_STBY", &InputMappings[68]},
  {"INST_PNL_DIMMER_INC", &InputMappings[52]},
  {"LIGHTS_TEST_SW_OFF", &InputMappings[53]},
  {"ENG_ANTIICE_SW_ON", &InputMappings[32]},
  {"ENG_ANTIICE_SW_OFF", &InputMappings[31]},
  {nullptr, nullptr},
  {"RADAR_SW_DEC", &InputMappings[88]},
  {"WARN_CAUTION_DIMMER_INC", &InputMappings[57]},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {"R_GEN_SW_OFF", &InputMappings[11]},
  {nullptr, nullptr},
  {"INS_SW_DEC", &InputMappings[78]},
  {"CHART_DIMMER_DEC", &InputMappings[39]},
  {nullptr, nullptr},
  {"RADAR_SW_INC", &InputMappings[89]},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {"BLEED_AIR_KNOB_NORM", &InputMappings[15]},
  {"INS_SW_INC", &InputMappings[79]},
  {"CHART_DIMMER_INC", &InputMappings[40]},
  {"L_GEN_SW_NORM", &InputMappings[10]},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {"CB_LG", &InputMappings[64]},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {"COCKKPIT_LIGHT_MODE_SW_DAY", &InputMappings[41]},
  {nullptr, nullptr},
  {"INST_PNL_DIMMER", &InputMappings[50]},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {"WARN_CAUTION_DIMMER", &InputMappings[55]},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {"CONSOLES_DIMMER_DEC", &InputMappings[45]},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {"FLIR_SW_ON", &InputMappings[69]},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {"CONSOLES_DIMMER_INC", &InputMappings[46]},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {"BATTERY_SW_ON", &InputMappings[8]},
  {"LST_NFLR_SW_ON", &InputMappings[81]},
  {nullptr, nullptr},
  {"CONSOLES_DIMMER", &InputMappings[44]},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {"R_GEN_SW_NORM", &InputMappings[12]},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {"BATTERY_SW_OFF", &InputMappings[7]},
  {"L_GEN_SW_OFF", &InputMappings[9]},
  {"LST_NFLR_SW_OFF", &InputMappings[80]},
  {nullptr, nullptr},
  {"CABIN_TEMP_DEC", &InputMappings[25]},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {"CABIN_TEMP", &InputMappings[24]},
  {"BLEED_AIR_KNOB_L_OFF", &InputMappings[14]},
  {"CANOPY_SW_OPEN", &InputMappings[60]},
  {nullptr, nullptr},
  {"BATTERY_SW_ORIDE", &InputMappings[6]},
  {"WSHIELD_ANTI_ICE_SW_OFF", &InputMappings[4]},
  {nullptr, nullptr},
  {"INS_SW_NAV", &InputMappings[74]},
  {"CABIN_TEMP_INC", &InputMappings[26]},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {"FLIR_SW_OFF", &InputMappings[67]},
  {"CABIN_PRESS_SW_POS0", &InputMappings[21]},
  {"BLEED_AIR_KNOB_R_OFF", &InputMappings[16]},
  {"CABIN_PRESS_SW_POS1", &InputMappings[22]},
  {"CABIN_PRESS_SW_POS2", &InputMappings[23]},
  {"INS_SW_GB", &InputMappings[71]},
  {"LTD_R_SW_ARM", &InputMappings[83]},
  {"RADAR_SW_PULL", &InputMappings[90]},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {"CANOPY_SW_CLOSE", &InputMappings[58]},
  {"SUIT_TEMP", &InputMappings[35]},
  {"FLOOD_DIMMER", &InputMappings[47]},
  {"CB_HOOOK", &InputMappings[63]},
  {"RADAR_SW_EMERG(PULL)", &InputMappings[84]},
  {"INS_SW_GYRO", &InputMappings[72]},
  {"LIGHTS_TEST_SW_TEST", &InputMappings[54]},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {"WSHIELD_ANTI_ICE_SW_RAIN", &InputMappings[3]},
  {"ECS_MODE_SW_POS0", &InputMappings[27]},
  {"ECS_MODE_SW_POS1", &InputMappings[28]},
  {"ECS_MODE_SW_POS2", &InputMappings[29]},
  {"RADAR_SW_STBY", &InputMappings[86]},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {"SUIT_TEMP_DEC", &InputMappings[36]},
  {nullptr, nullptr},
  {"FLOOD_DIMMER_DEC", &InputMappings[48]},
  {nullptr, nullptr},
  {"DEFOG_HANDLE", &InputMappings[0]},
  {"BLEED_AIR_KNOB_OFF", &InputMappings[13]},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {"RADAR_SW_OPR", &InputMappings[85]},
  {nullptr, nullptr},
  {"SUIT_TEMP_INC", &InputMappings[37]},
  {"INS_SW_TEST", &InputMappings[70]},
  {"FLOOD_DIMMER_INC", &InputMappings[49]},
  {"COCKKPIT_LIGHT_MODE_SW_NVG", &InputMappings[43]},
  {"INS_SW_IFA", &InputMappings[73]},
  {"INS_SW_GND", &InputMappings[75]},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {"WSHIELD_ANTI_ICE_SW_ANTI_ICE", &InputMappings[5]},
  {"CHART_DIMMER", &InputMappings[38]},
  {"BLEED_AIR_KNOB_DEC", &InputMappings[17]},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {"BLEED_AIR_KNOB_INC", &InputMappings[18]},
  {"FCS_BIT_SW_RELEASE", &InputMappings[66]},
  {"CANOPY_SW_HOLD", &InputMappings[59]},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {nullptr, nullptr},
  {"COCKKPIT_LIGHT_MODE_SW_NITE", &InputMappings[42]},
};

// Shared recursive hash implementation for display label lookup
constexpr uint16_t labelHash(const char* s);


// Preserve existing signature
constexpr uint16_t inputHash(const char* s) { return labelHash(s); }

inline const InputMapping* findInputByLabel(const char* label) {
  uint16_t startH = inputHash(label) % 191;
  for (uint16_t i = 0; i < 191; ++i) {
    uint16_t idx = (startH + i >= 191) ? (startH + i - 191) : (startH + i);
    const auto& entry = inputHashTable[idx];
    if (!entry.label) continue;
    if (strcmp(entry.label, label) == 0) return entry.mapping;
  }
  return nullptr;
}
