#define LABEL_SET_NAME        "LEFT_PANEL_CONTROLLER"
#define HAS_HID_MODE_SELECTOR 0
#define MODE_DEFAULT_IS_HID   0
#define LABEL_SET_FULLNAME    "CockpitOS Left Panel Controller"
#define HAS_LEFT_PANEL_CONTROLLER
